version: '3'
services:
  postgresql:
    image: postgres
    container_name: service
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=service
      - POSTGRES_DATABASE=service
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-service
    ports:
      - "6379:6379"
    