export const user = [
    {
        "_id": "6462cb6a44e30044726df67d",
        "isActive": true,
        "balance": "$2,245.64",
        "picture": "http://placehold.it/32x32",
        "age": 39,
        "eyeColor": "green",
        "name": "Lara Alford",
        "gender": "male",
        "company": "MAGNINA",
        "email": "laraalford@magnina.com",
        "phone": "+1 (988) 459-2688",
        "address": "272 Menahan Street, Homeland, Arkansas, 7062"
      },
      {
        "_id": "6462cb6a190372f2c66205fa",
        "isActive": true,
        "balance": "$2,929.87",
        "picture": "http://placehold.it/32x32",
        "age": 34,
        "eyeColor": "blue",
        "name": "Fox Stewart",
        "gender": "male",
        "company": "KEGULAR",
        "email": "foxstewart@kegular.com",
        "phone": "+1 (812) 540-2502",
        "address": "114 Kenilworth Place, Boomer, Minnesota, 9758"
      },
      {
        "_id": "6462cb6a0734cf18e27c7544",
        "isActive": false,
        "balance": "$2,668.66",
        "picture": "http://placehold.it/32x32",
        "age": 29,
        "eyeColor": "blue",
        "name": "Kristin Frazier",
        "gender": "female",
        "company": "COMTRAK",
        "email": "kristinfrazier@comtrak.com",
        "phone": "+1 (826) 518-2036",
        "address": "267 Quay Street, Wilsonia, Florida, 4534"
      },
      {
        "_id": "6462cb6aa4d079e220ef6e13",
        "isActive": false,
        "balance": "$3,855.77",
        "picture": "http://placehold.it/32x32",
        "age": 24,
        "eyeColor": "green",
        "name": "Jeanine Carney",
        "gender": "female",
        "company": "ZINCA",
        "email": "jeaninecarney@zinca.com",
        "phone": "+1 (925) 462-3260",
        "address": "301 Johnson Avenue, Hayes, Michigan, 7005"
      },
      {
        "_id": "6462cb6a4df9b9b77d7d73c9",
        "isActive": true,
        "balance": "$1,847.86",
        "picture": "http://placehold.it/32x32",
        "age": 30,
        "eyeColor": "brown",
        "name": "Enid Blanchard",
        "gender": "female",
        "company": "FORTEAN",
        "email": "enidblanchard@fortean.com",
        "phone": "+1 (890) 584-3512",
        "address": "816 Beverley Road, Williamson, Wyoming, 3020"
      },
      {
        "_id": "6462cb6aac5c1898b5882f05",
        "isActive": true,
        "balance": "$2,789.52",
        "picture": "http://placehold.it/32x32",
        "age": 40,
        "eyeColor": "blue",
        "name": "Roxie Garrison",
        "gender": "female",
        "company": "TOYLETRY",
        "email": "roxiegarrison@toyletry.com",
        "phone": "+1 (875) 409-2268",
        "address": "966 Kermit Place, Devon, Arizona, 2481"
      },
      {
        "_id": "6462cb6a1afdffb5ae955dcb",
        "isActive": true,
        "balance": "$3,502.84",
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "eyeColor": "green",
        "name": "Kayla Baird",
        "gender": "female",
        "company": "OCEANICA",
        "email": "kaylabaird@oceanica.com",
        "phone": "+1 (929) 486-3208",
        "address": "895 Remsen Avenue, Grazierville, Georgia, 9119"
      }
]